spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
server.port=1111

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ranjitavaddebail001@gmail.com
spring.mail.password=rlnblgatecwqkhlo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.key.id=rzp_test_SkaDHiEr5YM0xu
razorpay.key.secret=j1uAWBOXpTkG90HCsa5hIPDL

cloudinary.cloud.name=dok9rgmy1
cloudinary.api.key=316134237756421
cloudinary.api.secret=Napgao6CS4wJSlND14oO3hvkTAY